import React from 'react';
import { TrendingUp, Activity, AlertTriangle } from 'lucide-react';

const PredictionPage = () => {
    return (
        <div className="pt-24 min-h-screen bg-primary-dark text-white px-6">
            <div className="container mx-auto max-w-6xl">
                <div className="flex items-center gap-4 mb-8">
                    <div className="w-12 h-12 rounded-xl bg-accent-cyan/20 flex items-center justify-center text-accent-cyan">
                        <TrendingUp size={24} />
                    </div>
                    <div>
                        <h1 className="text-3xl font-bold">Market Predictions</h1>
                        <p className="text-gray-400">AI-driven price forecasts and trend analysis.</p>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    {/* Prediction Cards Placeholder */}
                    {[1, 2, 3].map((item) => (
                        <div key={item} className="bg-primary-mid border border-white/10 rounded-xl p-6">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h3 className="text-lg font-bold">JKH.N0000</h3>
                                    <p className="text-sm text-gray-400">John Keells Holdings</p>
                                </div>
                                <span className="bg-green-500/20 text-green-400 text-xs font-bold px-2 py-1 rounded">Bullish</span>
                            </div>
                            <div className="h-32 bg-white/5 rounded-lg mb-4 flex items-center justify-center">
                                <Activity className="text-gray-600" />
                            </div>
                            <div className="flex justify-between items-center text-sm">
                                <span className="text-gray-400">Predicted (7d):</span>
                                <span className="font-bold text-white">192.50 (+3.5%)</span>
                            </div>
                        </div>
                    ))}
                </div>

                <div className="mt-8 bg-blue-500/10 border border-blue-500/20 rounded-xl p-4 flex items-start gap-3">
                    <AlertTriangle className="text-blue-400 shrink-0 mt-0.5" size={20} />
                    <div>
                        <h4 className="text-blue-400 font-bold text-sm">Disclaimer</h4>
                        <p className="text-blue-300/80 text-xs mt-1">
                            Predictions are generated by AI models based on historical data and should not be taken as financial advice. Always do your own research.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default PredictionPage;
